// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWYRzuJFRcY8idoWr9HJkwBk4SFEoymhM',
    appId: '1:110031330317:android:d748b4aa0aa7fffe130944',
    messagingSenderId: '110031330317',
    projectId: 'wedding-planner-84457',
    databaseURL: 'https://wedding-planner-84457-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wedding-planner-84457.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSrsKi_dIXgMhtfLMSurYaniPn7OK4Mrw',
    appId: '1:110031330317:ios:0dbc38de584e45f5130944',
    messagingSenderId: '110031330317',
    projectId: 'wedding-planner-84457',
    databaseURL: 'https://wedding-planner-84457-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wedding-planner-84457.appspot.com',
    iosClientId: '110031330317-9chgko48rar7t85rju6fg0aseutk8q1u.apps.googleusercontent.com',
    iosBundleId: 'com.juliaanokhina.weddingPlanner',
  );
}
